# -*- coding: utf-8 -*-
"""十進制轉換.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A-9UhJvDb7TCR9S6Vzv64O9ce3FbomVI
"""

def decimal_to_binary(decimal):
    binary = ""
    if decimal == 0:
        return "0"
    while decimal > 0:
        remainder = decimal % 2
        binary = str(remainder) + binary
        decimal = decimal // 2
    return binary

def decimal_to_hexadecimal(decimal):
    hexadecimal = ""
    hex_chars = "0123456789ABCDEF"
    if decimal == 0:
        return "0"
    while decimal > 0:
        remainder = decimal % 16
        hexadecimal = hex_chars[remainder] + hexadecimal
        decimal = decimal // 16
    return hexadecimal

# 讀取用戶輸入的十進位數字
decimal_number = int(input("請輸入一個十進位數字 (0-255): "))

# 轉換並輸出結果
binary_result = decimal_to_binary(decimal_number)
hex_result = decimal_to_hexadecimal(decimal_number)
print("二進位為: {}".format(binary_result))
print("十六進位為: {}".format(hex_result))